export const theme = {
  bg: "#f7f3ea",
  bgSoft: "#eef6e1",
  bgStrong: "#e4efd7",
  panel: "#fffaf3",
  panelStrong: "#f2eee4",
  line: "#d8dcc9",
  text: "#20362d",
  buttonText: "#173126",
  muted: "#5f7267",
  primary: "#7aa56d",
  primaryStrong: "#658d5a",
  gradientStart: "#4f7658",
  gradientEnd: "#8eb26d",
  accent: "#f2c38b",
  accentStrong: "#e9b26d",
  languageColor: "#3f6f9f",
  frameworkColor: "#7a5aa6",
  toolColor: "#b06a3c",
  skillColor: "#2f8a72",
  glow: "rgba(122, 165, 109, 0.26)",
  shadow: "rgba(42, 59, 36, 0.14)",
  overlay: "rgba(35, 44, 35, 0.36)",
  badgeBg: "rgba(122, 165, 109, 0.12)",
  badgeBorder: "rgba(122, 165, 109, 0.22)",
  surfaceAlt: "rgba(255, 255, 255, 0.05)",
  bamboo: "#dfecc7",
  panda: "#2d2d2d",
  pandaSoft: "#eee9e1",
  white: "#ffffff",
  fontBody: "Arial, Helvetica, sans-serif",
  fontDisplay: "Arial, Helvetica, sans-serif",
  fontSizeXs: "0.72rem",
  fontSizeSm: "0.92rem",
  fontSizeBase: "1rem",
  fontSizeLead: "1.08rem",
  fontSizeHeroGreeting: "1.05rem",
  fontSizeHeroName: "clamp(1.5rem, 2.4vw, 2.4rem)",
  fontSizeHeroRoleLabel: "1.05rem",
  fontSizeHeroRole: "clamp(2.1rem, 3vw, 3.5rem)",
  fontSizeNav: "0.9rem",
  fontSizeCardTitle: "1.28rem",
  fontSizeDetail: "0.96rem",
  fontSizeTitle: "clamp(2.1rem, 3vw, 3.5rem)",
  weightRegular: 400,
  weightMedium: 500,
  weightSemibold: 600,
  weightBold: 700,
  weightExtraBold: 800,
};

export const muiThemeOptions = {
  typography: {
    fontFamily: theme.fontBody,
    fontWeightRegular: theme.weightRegular,
    fontWeightMedium: theme.weightMedium,
    fontWeightBold: theme.weightBold,
    h1: {
      fontFamily: theme.fontDisplay,
      fontSize: theme.fontSizeTitle,
      fontWeight: theme.weightBold,
      lineHeight: 1.05,
    },
    h2: {
      fontFamily: theme.fontDisplay,
      fontWeight: theme.weightBold,
      lineHeight: 1.05,
    },
    h3: { fontWeight: theme.weightBold },
    body1: { fontSize: theme.fontSizeBase, lineHeight: 1.6 },
    body2: { fontSize: theme.fontSizeSm, lineHeight: 1.5 },
  },
  palette: {
    primary: { main: theme.primary, dark: theme.primaryStrong },
    secondary: { main: theme.accent, dark: theme.accentStrong },
    text: { primary: theme.text, secondary: theme.muted },
    background: { default: theme.bg, paper: theme.panel },
  },
  shape: { borderRadius: 12 },
};

export const themeVars = {
  "--bg": theme.bg,
  "--bg-soft": theme.bgSoft,
  "--bg-strong": theme.bgStrong,
  "--panel": theme.panel,
  "--panel-strong": theme.panelStrong,
  "--line": theme.line,
  "--text": theme.text,
  "--button-text": theme.buttonText,
  "--muted": theme.muted,
  "--primary": theme.primary,
  "--primary-strong": theme.primaryStrong,
  "--gradient-start": theme.gradientStart,
  "--gradient-end": theme.gradientEnd,
  "--accent": theme.accent,
  "--accent-strong": theme.accentStrong,
  "--language-color": theme.languageColor,
  "--framework-color": theme.frameworkColor,
  "--tool-color": theme.toolColor,
  "--skill-color": theme.skillColor,
  "--glow": theme.glow,
  "--shadow": theme.shadow,
  "--overlay": theme.overlay,
  "--badge-bg": theme.badgeBg,
  "--badge-border": theme.badgeBorder,
  "--surface-alt": theme.surfaceAlt,
  "--bamboo": theme.bamboo,
  "--panda": theme.panda,
  "--panda-soft": theme.pandaSoft,
  "--white": theme.white,
  "--font-body": theme.fontBody,
  "--font-display": theme.fontDisplay,
  "--font-size-xs": theme.fontSizeXs,
  "--font-size-sm": theme.fontSizeSm,
  "--font-size-base": theme.fontSizeBase,
  "--font-size-lead": theme.fontSizeLead,
  "--font-size-hero-greeting": theme.fontSizeHeroGreeting,
  "--font-size-hero-name": theme.fontSizeHeroName,
  "--font-size-hero-role-label": theme.fontSizeHeroRoleLabel,
  "--font-size-hero-role": theme.fontSizeHeroRole,
  "--font-size-nav": theme.fontSizeNav,
  "--font-size-card-title": theme.fontSizeCardTitle,
  "--font-size-detail": theme.fontSizeDetail,
  "--font-size-title": theme.fontSizeTitle,
  "--weight-regular": theme.weightRegular,
  "--weight-medium": theme.weightMedium,
  "--weight-semibold": theme.weightSemibold,
  "--weight-bold": theme.weightBold,
  "--weight-extra-bold": theme.weightExtraBold,
};
